version: "3"
services:
    condas:
        container_name: condas
        build: ./ana
        image: udemy_condas
        volumes:
            - ./ana/prog/:/tmp/prog
        ports:
            - "8889:8889"
        stdin_open: true
        tty: true 
        command: jupyter notebook --NotebookApp.token='admin' --no-browser --allow-root --ip=0.0.0.0 --port=8889

